### ISSUE TITLE
different dates ?!

### ISSUE THREAD

**Issue by a1exb1** [novalagung/NVDate#3]
NSLog(@"%@, %d, %@", _firstDateOfCalender.date, (int)_firstDateOfCalender.day, [_firstDateOfCalender stringValueWithFormat:@"dd/MM/yyyy"]);

.date and nvdate.day give different days: 

2014-05-26 22:00:00 +0000, 27, 27/05/2014

**Comment by novalagung** [comment]
I just found out why `.date` and `nvdate.day` gave different result. It because `timezone`.

When you put `NSDate` object in log, it'll *always* return in `UTC` format. You may see `+0000` in the tail. But, when you access each component (like days/month/year/etc) or get string value of the date, it  will return a value in your locale timezone. That's why the value is different.

I've push some updates, to change the timezone. By default NVDate will use local timezone.

**Comment by a1exb1** [comment]
Well spotted n1
